### ISSUE TITLE
安卓位移动画

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#300]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1]
- 相关模块:[eg.Host/Service/Account]

#### 现象

使用Animated.View实现位移动画，在安卓上能明显感觉有卡顿，掉帧，在ios上很流畅（掉帧数较少），类似效果在你们的demo上也存在，是否有优化的办法？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by fishle** [comment]
demo上的位移动画是指的第三方库demo下面的AnimTranslationDemo这个演示动画吗？

**Comment by mirse** [comment]
你用的手机是？我当时用的是一加3测试的

**Comment by fishle** [comment]
小米8 lite, 可以试试官网的优化建议：

https://reactnative.cn/docs/animations/#%E5%90%AF%E7%94%A8%E5%8E%9F%E7%94%9F%E5%8A%A8%E7%94%BB%E9%A9%B1%E5%8A%A8

如果你发现你的动画丢帧（低于 60 帧每秒），可以尝试使用setNativeProps或者shouldComponentUpdate来优化它们。Or you could run the animations on the UI thread rather than the JavaScript thread with the useNativeDriver option. 你还可以考虑将部分计算工作放在动画完成之后进行，这时可以使用InteractionManager。你还可以使用应用内的开发者菜单中的“FPS Monitor”工具来监控应用的帧率。

**Comment by mirse** [comment]
好的，谢谢

**Comment by fishle** [comment]
有空试试这2个建议
